mariadb-corporation/mariadb-columnstore-api

docs/changelog.rst, docs/reference/bulk_insert.rst, docs/reference/types.rst, libmcsapi/mcsapi_bulk.h, src/mcsapi_bulk.cpp, test/bad-usage.cpp, version.h
Add a resetRow method to clear the current set rows without writing
them.
Additionally this change fixes documentation issues and removes a file
that was accidentally committed.
=> MCOL-990 Add resetRow method

CMakeLists.txt
Including the binary directory allows the source and binary directories to be in different places.
=> Allow out-of-source builds

CMakeLists.txt, README.md, docs/building.rst, src/CMakeLists.txt, src/mcsapi_types.cpp
The std::get_time function was not in GCC 4.9 which makes builds on Debian
8 quite problematic. The function can be substituted with the strptime
POSIX function.
=> Fix Debian 8 build failures

java/CMakeLists.txt
The Java library has an underscore prefix in CMake < 3.0 due to a bug in
the SWIG CMake wrapper. This patch adds a copy of the macro modified to
trim off the added prefix.
=> MCOL-1044 Fix Java library prefix

docs/reference/driver.rst, src/util_commands.cpp, test/bad-usage.cpp
We were previously ignoring table lock failures and just allowing the
bulk insert to continue anyway. Now a pre-existing table lock is a hard
failure.
=> MCOL-1079 Raise exception when table lock fails

README.md
Added Debian packet dependencies to documentation and changed to use Java SDK 8 instead of 7 for Debian  8
=> MCOL-1087 - Debian package dependencies added

src/mcsapi_bulk.cpp, src/util_commands.cpp, src/util_commands.h
We weren't sending the DBRM rollback command which left an orphaned
transaction inside the DBRM when a rollback occurred. This wasn't
obvious until mcsadmin restart.
=> MCOL-1108 Add DBRM rollback

src/mcsapi_types.cpp, test/dataconvert-decimal.cpp
If a decimal was set via a string:
1. the number of digits could cause an overflow and bad data
2. negative numbers were corrupted
This patch trims numbers that are too large to store and fixes support
for negative numbers
=> MCOL-1133 Fix Decimal trunc and neg

src/mcsapi_bulk.cpp, src/mcsapi_driver.cpp, test/commit.cpp
If an mcsapi instance is currently running a second mcsapi instance will
end up with the same txnID since the sessionID is fixed and the engine
matches session to txn. This patch randomizes sessionID for each
instance.
=> MCOL-1147 Fix sessionID/txnID reuse

libmcsapi/mcsapi_types.h, src/mcsapi_driver.cpp, src/mcsapi_types.cpp, src/mcsapi_types_impl.h
The memory leak fix to system catalog caused a double-free when the
references were cleaned up and triggered destructors.
This fix makes sure only the final cleanup deletes the system catalog
allocations
=> MCOL-1168 Fix system catalog regression

src/mcsapi_bulk.cpp, test/CMakeLists.txt, test/mcol1160.cpp
This patch requires the corresponding patch in the engine code to work
correctly (but won't stop API functioning without it).
It removes the second connection on commit so that the dict LBID flush
tracking doesn't get lost. It also adds a test
=> MCOL-1160 Fix dictionary flushing

CMakeLists.txt, src/CMakeLists.txt, src/mcsapi_types.cpp, src/mcsapi_types_impl.h, test/dataconvert-decimal.cpp
Our own decmial handling was breaking on lots of edge cases. So this
patch switches to boost::multiprecision for decimal handling.
=> MCOL-1133 Use boost for decimal types

docs/changelog.rst, docs/reference/types.rst, src/mcsapi_types.cpp, test/system-catalog.cpp
ColumnStore's system catalog is lower case so this patch makes system
catalog searches case insensitive. Therefore a user who created a table
with mixed/upper case naming can still reference the table.
=> MCOL-1213 system catalog is lower case

docs/compiling.rst, src/util_commands.cpp, src/util_network.cpp, src/util_network.h
If the decompression buffer was used twice a double-free event would
occur causing a segfault. This fixes that problem and an error in the
compiling documentation.
No test since it requires a remote connection to trigger. You need a
table with a large amount of columns so that the decompression will be
used for the read of the system catalog and the HWM data.
=> MCOL-1245 Fix decompression double-free

java/build.gradle, java/javamcsapi.i, java/src/test/java/com/mariadb/columnstore/api/StatusTest.java, python/CMakeLists.txt, python/pymcsapi.i, python/test/test_basic.py, python/test/test_status.py
- setColumn() has now two output values: ColumnStoreBulkInsert and status in Java and Python.
- relevant regression tests added
- added a Swig type-map to simplify Java enums without initializes
- includes one usability bugfix for manually executing the Java tests through gradle from the Java directory resulting from MCOL-1261
=> MCOL-1321 status information output for setColumn()

src/mcsapi_types.cpp
Boost 1.65 in Ubuntu 18.04 appears to do weird things when calclating
the scale of '0'. For now we will just shortcut zero.
=> MCOL-1444 Fix Decimal for Ubuntu 18.04

README.md
removed devtoolset-4-gcc as its not needed any more
=> CentOS readme update

.gitignore, src/util_commands.cpp, src/util_network.cpp, src/util_network.h
Libuv runs the callbacks effectively in a separate thread which means
throwing execptions does nothing. Instead the error status/message
should be logged and thrown when state is checked.
=> MCOL-1453 Fix network error handling

src/mcsapi_bulk.cpp
If a table is already locked we need to rollback the transaction ID that
we have already created before throwing the error. Otherwise we are left
with stale transactions with no locks.
=> MCOL-1195 Clean up TXN when table already locked

README.md, java/docs/CMakeLists.txt, java/docs/sources.cmake.in, python/docs/sources.cmake.in
- fixed the pymcsapi and javamcsapi documentation for out of source builds
- changed the build instructions in Readme.md to install LaTeX on CentOS from ctan.org instead of CentOS's packet manager
=> MCOL-1566 - pymcsapi & javamcsapi documentation out of source fix - CentOS LaTeX build fix

python/test/test_basic.py, spark-connector/python/columnStoreExporter.py, spark-connector/python/test/test_column_store_SQL_generation.py, spark-connector/python/test/test_column_store_exporter.py, spark-connector/python/test/test_column_store_exporter.sh
Fixes an error in the python spark connector and makes it usable again.
Also adjusts the tests so that this error will be discovered through our regression test suite.
=> MCOL-1612 - Python spark connector fix

README.md
- added one more ctan installation dependency
- change LaTeX installation folder to /usr/sbin to be usable by sudo (during sudo make install)
=> MCOL-1566 - CentOS LaTeX installation instruction update

CMakeLists.txt, src/CMakeLists.txt, src/mcsapi_types.cpp, test/dataconvert-datetime.cpp
Internally we used std::get_time() where we could to do date/time
conversions. Unfortunately it appears every version of glibc has
different behaviour quirks with that function so switching to strptime()
instead.
=> MCOL-1720 Fix DateTime format failures

src/util_dataconvert.cpp, test/dataconvert-decimal.cpp, test/dataconvert-null.cpp
DECIMAL NULL is a variable length so we need to send the correct length
of data. This patch figures out the correct length and sends the correct
NULL accordingly.
=> MCOL-1322 Fix DECIMAL NULL for different sizes

docs/changelog.rst, docs/reference/driver.rst, libmcsapi/mcsapi_driver.h, src/mcsapi_driver.cpp, src/util_dataconvert.cpp, src/util_debug.cpp, src/util_debug.h, src/util_network.cpp, test/dataconvert-datetime.cpp
This branch does the following:
* Fix issue where line numbers and file names were only showing
util_debug entries
* Add debug levels to setDebug()
- 1 is less verbose and truncates at 1000 bytes
- 2 is as before
* Fix a bunch of GCC 8 compiler warnings
=> Improve the debugging output

spark-connector/scala/README.md, spark-connector/scala/build.gradle, spark-connector/scala/src/main/scala/com/mariadb/columnstore/api/connector/ColumnStoreExporter.scala, spark-connector/scala/src/test/scala/com/mariadb/columnstore/api/connector/ColumnStoreExporterTestFromWorker.scala
Introduced a new Scala Spark Connector function:
ColumnStoreExporter.exportFromWorkers("database", "table", RDD, [partitions], [path to Columnstore.xml])
It exports a RDD from the Worker instead of the Master. This decreased the ingestion time by 59% in my test case compared to ColumnStoreExporter.export()
I wasn't able to implement it for PySpark as its runJob() function seems different than Scala's.
To use exportFromWorkers() the bulk Write SDK and Columnstore.xml need to be installed on the Spark Driver and Workers. 
Added a simple test to the regression suite and executed it successfully on CentOS 7 and Windows 10.
=> MCOL-1362 - new Spark Scala export directly from workers
